name: Build

on:
  push:
    branches: [ "main" ]

jobs:
  windows-build:
    name: "Build on Windows with Spinnaker SDK"
    runs-on:
      - self-hosted
      - spinnaker
      - windows

    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Enable long paths
        run: |
          git config --global core.longpaths true
        shell: pwsh

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Get CMake 3.24
        uses: lukka/get-cmake@latest
        with:
          useCloudCache: false
          useLocalCache: true
          cmakeVersion: 3.24.3

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Package
        run: |
          cmake -B ${{github.workspace}}/pack -DCMAKE_BUILD_TYPE=Release -DNOTEST=1
          cmake --build ${{github.workspace}}/pack --config Release
          cpack --config ${{github.workspace}}/pack/CPackConfig.cmake -C Release -G ZIP

      - uses: actions/upload-artifact@v3
        with:
          name: windows-latest Release binaries
          path: ${{github.workspace}}/*.zip

  linux-build:
    name: "Build on Ubuntu with Spinnaker SDK"
    runs-on:
      - self-hosted
      - spinnaker
      - linux

    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Package
        run: |
          cmake -B ${{github.workspace}}/pack -DCMAKE_BUILD_TYPE=Release -DNOTEST=1
          cmake --build ${{github.workspace}}/pack --config Release
          cpack --config ${{github.workspace}}/pack/CPackConfig.cmake -C Release -G ZIP

      - uses: actions/upload-artifact@v3
        with:
          name: ubuntu-latest Release binaries
          path: ${{github.workspace}}/*.zip

  mac-build:
    name: "Build on Mac"
    runs-on: macos-latest

    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release -DNOTEST=1

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config Release
          cpack --config ${{github.workspace}}/build/CPackConfig.cmake -C Release -G ZIP

      - uses: actions/upload-artifact@v3
        with:
          name: macos-latest Release binaries
          path: ${{github.workspace}}/*.zip
