name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_TYPE: Release

jobs:
  test-blackfly:
    name: "Test on Windows with Blackfly"
    runs-on:
      - self-hosted
      - spinnaker
      - windows # pwsh, msvc
      - BFLY-U3-23S6M-C # for tests

    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Enable long paths
        run: |
          git config --global core.longpaths true
        shell: pwsh

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get CMake 3.24
        uses: lukka/get-cmake@latest
        with:
          useCloudCache: false
          useLocalCache: true
          cmakeVersion: 3.24.3

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -L blackfly --output-on-failure

  test-oryx:
    name: "Test on Windows with Oryx"
    runs-on:
      - self-hosted
      - spinnaker
      - windows # pwsh, msvc
      - ORX-10GS-51S5M-C # for tests

    permissions:
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Enable long paths
        run: |
          git config --global core.longpaths true
        shell: pwsh

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Get CMake 3.24
        uses: lukka/get-cmake@latest
        with:
          useCloudCache: false
          useLocalCache: true
          cmakeVersion: 3.24.3

      - name: Install MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64_x86

      - name: Configure
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}} -L oryx --output-on-failure
